version: '3.7'
services:
  db:
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=MilkTea
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root123456
      - MYSQL_HOST=db
    ports:
      - "3307:3306"
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
    restart: unless-stopped

#docker-compose up --build -d
